# Generated by Django 3.2.12 on 2022-02-28 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='name')),
                ('surname', models.CharField(max_length=40, verbose_name='surname')),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.CharField(max_length=400, verbose_name='quote')),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Handler.author')),
            ],
        ),
        migrations.CreateModel(
            name='QuoteBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(verbose_name='day')),
                ('fQuote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Handler.quote')),
            ],
        ),
    ]
