# Generated by Django 3.2.12 on 2022-03-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Handler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shareurl', models.SlugField(default='1111', max_length=4, verbose_name='surl_state')),
            ],
        ),
        migrations.AddField(
            model_name='quotebank',
            name='surl',
            field=models.SlugField(default='1111', max_length=4, unique=True, verbose_name='share-url'),
        ),
        migrations.AlterField(
            model_name='quotebank',
            name='day',
            field=models.DateField(verbose_name='date'),
        ),
    ]
