# Generated by Django 3.2.12 on 2022-03-04 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Handler', '0003_auto_20220304_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotebank',
            name='imgtype',
        ),
        migrations.AddField(
            model_name='quote',
            name='Background',
            field=models.CharField(choices=[('1.jpg', 'diamond'), ('2.jpg', 'heart'), ('3.jpg', 'round')], default='1.jpg', max_length=6, verbose_name='bg-image'),
        ),
    ]
