# Generated by Django 3.2.12 on 2022-03-07 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Handler', '0004_auto_20220304_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='afont',
            field=models.IntegerField(default=16, verbose_name='author-font'),
        ),
        migrations.AddField(
            model_name='quote',
            name='qfont',
            field=models.IntegerField(default=16, verbose_name='author-font'),
        ),
    ]
