# Generated by Django 3.2.12 on 2022-03-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Handler', '0006_auto_20220309_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='quote',
            field=models.TextField(max_length=300, verbose_name='quote'),
        ),
    ]
